---
# yamllint disable rule:line-length
# yamllint disable rule:comments
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/template/default"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/template/deno"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/template/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/template/rust"
    schedule:
      interval: "weekly"
