---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task -t tasks/toml.yml --list

  check:
    desc: Check TOML files
    silent: true
    cmds:
      - taplo check .
      - taplo format --check .
  fix:
    desc: Fix TOML files
    silent: true
    cmds:
      - taplo format .
